# Generated by Django 3.1.2 on 2020-10-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20201028_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fotoPerfil',
            field=models.FileField(default=None, upload_to='fotos'),
        ),
    ]
