# Generated by Django 3.1.2 on 2020-11-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_perfilusuario_fotoperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fotoPerfil',
        ),
    ]
