# Generated by Django 3.1.2 on 2020-10-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='stock',
            new_name='anio',
        ),
    ]
