# Generated by Django 3.1.2 on 2020-10-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20201013_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
