# Generated by Django 3.1.2 on 2020-10-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='fecha_ingreso',
            field=models.CharField(max_length=50),
        ),
    ]
