# Generated by Django 3.1.2 on 2020-10-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_20201015_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('detalle', models.TextField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
