# Generated by Django 3.1.2 on 2020-10-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_20201028_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto2',
            new_name='Auto',
        ),
    ]
