# Generated by Django 3.1.2 on 2020-10-31 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_auto_20201031_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(default=None, upload_to='fotos')),
            ],
        ),
        migrations.AlterField(
            model_name='perfilauto',
            name='imagenAuto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.imagenauto'),
        ),
    ]
