# Generated by Django 3.1.2 on 2020-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_auto_20201031_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilauto',
            name='imagenAuto',
            field=models.FileField(default=None, upload_to='fotos'),
        ),
        migrations.DeleteModel(
            name='ImagenAuto',
        ),
    ]
