# Generated by Django 3.1.2 on 2020-11-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_auto_20201031_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagenAuto',
            field=models.FileField(default=None, upload_to='fotos'),
        ),
        migrations.DeleteModel(
            name='PerfilAuto',
        ),
    ]
