# Generated by Django 3.1.2 on 2020-11-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_auto_20201101_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='año',
            new_name='anio',
        ),
    ]
