# Generated by Django 3.1.2 on 2020-11-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0013_auto_20201103_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='anio',
            new_name='año',
        ),
    ]
